Fiola merge
flatironinstitute/CaImAn pull request #914
Opened 2021-09-13 15:10 UTC by caichangjia

# Description

Merge FIOLA into CaImAn

# Type of change
Please delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)
Add fiola class for real-time processing of fluorescence imaging data;
add demo_fiola.py file as demo;
add test_fiola.py file for tests;

2021-09-13 19:18 UTC, pgunn requested changes
If you feel like it you could also add typing to the function declarations, although if you don't want to do that, it's fine. You don't need to address all my comments.

My reasoning behind preferring log phrasing like "Doing this" rather than "Do this" is that using the imperative voice *only* when the user is being asked to do something helps distinguish "User must do this" from "program is currently doing this".

2021-09-13 19:18 UTC, pgunn commented on caiman/fiola/gpu_mc_nnls.py
> +        self.Nr = tf.signal.ifftshift(tf.range(-tf.experimental.numpy.fix(self.nr / 2.), tf.math.ceil(self.nr / 2.)))
If you can think of a way to do some abstraction to have this code be less repetitive (and operate less in-place), that'd be great.

2021-09-13 19:18 UTC, pgunn commented on caiman/fiola/gpu_mc_nnls.py
> +        idx = tf.transpose(tf.stack([n_batches, tf.squeeze(sh_x-1,axis=1), tf.squeeze(sh_y,axis=1)]))
Is there a more efficient, readable, and perhaps abstract way to write this block of code?

2021-09-13 19:18 UTC, pgunn commented on caiman/fiola/gpu_mc_nnls.py
> +        pass as inputs the new Y, and the old X. see  https://angms.science/doc/NMF/nnls_pgd.pdf
document what it returns

2021-09-13 19:18 UTC, pgunn commented on caiman/fiola/signal_analysis_online.py
> +        logging.info('skip template matching')
skipping template matching

2021-09-13 19:18 UTC, pgunn commented on caiman/fiola/signal_analysis_online.py
> +                logging.info(f'Adaptive threshold factor is lower than minimal theshold: {minimal_thresh}, choose thresh factor to be {minimal_thresh}')
Should this be an error or a warning? If it's just info people will usually not notice.

2021-09-13 19:18 UTC, pgunn commented on caiman/fiola/signal_analysis_online.py
> +            logging.info('Adaptive threshold fails, automatically choose thresh factor to be 3')
Should this be an error?

2021-09-13 19:18 UTC, pgunn commented on caiman/fiola/signal_analysis_online.py
> +        raise ValueError('other methods are not implemented yet')
Prefer to say "Method {method} not supported" or something like that; user might've made a typo when requesting a method.

2021-09-13 19:18 UTC, pgunn commented on caiman/fiola/signal_analysis_online.py
> +    logging.info(f'final threshhold equals: {thresh2/std}')
"Final threshold: {thresh2/std}"

2021-09-13 19:18 UTC, pgunn commented on caiman/fiola/signal_analysis_online.py
> +        plt.pause(5)
Probably fine, but I wonder if there's a better answer than an arbitrary pause of 5 seconds

2021-09-13 19:18 UTC, pgunn commented on caiman/fiola/signal_analysis_online.py
> +        plt.title('distribution of spikes')
"Spike distribution"

2021-09-13 19:18 UTC, pgunn commented on caiman/tests/test_fiola.py
> +    fnames = fnames                 # name of the movie, we don't put a name here as movie is already loaded above
This doesn't do anything

2021-09-13 19:18 UTC, pgunn commented on demos/general/demo_fiola.py
> +from threading import Thread
Flip these lines to alphabetise

2021-09-13 19:18 UTC, pgunn commented on demos/general/demo_fiola.py
> +    movie_folder = ['/home/nel/NEL-LAB Dropbox/NEL/Papers/VolPy_online/data/voltage_data',
These hardcoded paths are not going to be present

2021-09-13 19:18 UTC, pgunn commented on demos/general/demo_fiola.py
> +        plt.figure(); plt.imshow(mov.mean(0), vmax=np.percentile(mov.mean(0), 99.9)); plt.title('Mean img')
separate lines

2021-09-13 19:18 UTC, pgunn commented on demos/general/demo_fiola.py
> +            plt.figure(); plt.imshow(mask.mean(0)); plt.title('Masks')
separate lines

2021-09-13 19:18 UTC, pgunn commented on demos/general/demo_fiola.py
> +        plt.figure(); plt.plot(shifts);plt.legend(['x shifts', 'y shifts']); plt.title('shifts'); plt.show()
separate lines

2021-09-13 19:18 UTC, pgunn commented on demos/general/demo_fiola.py
> +        os.remove(log_file)
Is removing log files something the user will usually want?

2021-09-15 14:21 UTC, caichangjia commented on caiman/fiola/gpu_mc_nnls.py
> +os.environ["CUDA_VISIBLE_DEVICES"] = "0";
it sets particular gpu for running the code, but seems not necessary in our case

2021-09-15 15:15 UTC, pgunn commented
Another "would be nice" would be to use type annotations for arguments and return values, although I can add this in afterwards if you prefer.

2021-09-15 15:49 UTC, caichangjia commented on caiman/fiola/fiola.py
> +gpus = tf.config.experimental.list_physical_devices('GPU')
It is the default way to limit GPU memory in tensorflow2 and it is necessary for our code. I don't find an alternative unfortunately.

2021-09-23 14:39 UTC, pgunn approved these changes

2021-09-23 17:27 UTC, merged